### ISSUE TITLE
Finish roadmap

### ISSUE THREAD

**Issue by josessolmaximo** [josessolmaximo/budgetify-ios#11]
- [x] Add a review before adding to view
- [x] Change NavigationView title to inline for iPhone 8
- [x] Add keyboard toolbar
